# Generated by Django 3.1.4 on 2020-12-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
