# Generated by Django 3.1.4 on 2020-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0002_delete_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
